#################################
#### APPLICATION BOT DISCORD ####
#################################

FROM node:18

# Information sur l'application
LABEL description="Bot Discord LNB de gestion GvG"
LABEL authors="OLIVIER Fabien"
LABEL release-date="Mars 2024"
LABEL version="3"

WORKDIR /bot

ADD /bot .

RUN npm install

CMD ["npm", "start"]

